### ISSUE TITLE
Erreur SQL à l'activation du Plugin

### ISSUE THREAD

**Issue by mamatdv** [Micka41/plugin-hilink#1]
Bonjour, 

je rencontre une erreur SQL lorsque j'active le plugin.

[MySQL] Error code : 22007 (1366). Incorrect integer value: '' for column `jeedom`.`cmd`.`isVisible` at row 1 : INSERT INTO `cmd` SET `id` = :id, `logicalId` = :logicalId, `generic_type` = :generic_type, `eqType` = :eqType, `name` = :name, `order` = :order, `type` = :type, `subType` = :subType, `eqLogic_id` = :eqLogic_id, `isHistorized` = :isHistorized, `unite` = :unite, `configuration` = :configuration, `template` = :template, `display` = :display, `value` = :value, `isVisible` = :isVisible, `alert` = :alert

Jeedom 4.0.61 a été fraichement installé et c'est le premier plugin qui est installé.
Si besoin, je peux donné accès à la machine

**Comment by Micka41** [comment]
Bonjour,
Je n'utilise plus le plugin, je ne fais donc plus de maintenance dessus. Un autre existe sur le market avec des fonctionnalités équivalente.

**Comment by mamatdv** [comment]
Arf dommage. L'autre plugin n'est pas aussi bien que le tiens. 
On ne peut pas faire d'interaction avec les SMS.

Je vais forker et essayer de corriger.
